import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: " Mittal Hospital",
  description: "Generated by create next app",
  icons: [
    {
      rel: 'icon',
      type: 'image/png',
      sizes: '160x160',
      url: 'mainLogo.png',
    }
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
